mk_api:
    resource: "@MKApiBundle/Controller/"
    type:     annotation
    prefix:   /api

mk_user:
    resource: "@MKUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
