# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        MK\UserBundle\Entity\User: 
            id: mk.user.password_encoder

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        mk_user_service:
            id: mk.user.provider
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: /
            anonymous: ~
            provider: mk_user_service
            guard: 
                authenticators:
                    - mk.login.form_authenticator
            logout:
                path:   /logout
                target: /
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
