# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    encoders:
        MK\UserBundle\Entity\User: 
            id: mk.user.password_encoder

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        mk_user_service:
            id: mk.user.provider
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: /
            anonymous: ~
            provider: mk_user_service
            guard: 
                authenticators:
                    - mk.login.form_authenticator
                    - mk.jwt.authenticator
                entry_point: mk.login.form_authenticator
                
            logout:
                path:   /logout
                target: /
        api:
            pattern: ^/api/
            anonymous: true
            stateless: true
            #access_denied_handler: mk.api.access_denied.handler
            guard: 
                authenticators:
                    - mk.jwt.authenticator
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [GET] }
        - { path: ^/api, roles: ROLE_SUPER_ADMIN, methods: [POST, PUT, PUSH, DELETE] }
       # - { path: ^/api, roles: ROLE_USER }