<?php

namespace DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    public function getParents()
    {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT a FROM DataBundle:Category a WHERE a.parent = 0')
                        ->getResult();
    }

    public function getChildren($parent)
    {
        return $this->getEntityManager()
                        ->createQuery(
                                'SELECT a FROM DataBundle:Category a WHERE a.parent = :par')
                        ->setParameter('par', $parent)
                        ->getResult();
    }

}
