<?php

namespace DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends EntityRepository {

    public function findAllEntities($currentPage = 1, $limit) {
        $query = $this->createQueryBuilder('b')
                ->getQuery();

        $query->setFirstResult($limit * ($currentPage - 1)) // Offset
                ->setMaxResults($limit); // Limit

        $result = $query->getResult();
        return $result;
    }

    public function countAllEntities() {
        $query = $this->getEntityManager()
                ->createQuery(
                'SELECT  count(a) FROM DataBundle:Gallery a');
        $count = $query->getSingleScalarResult();
        return $count;
    }

    public function paginate($dql, $page = 1, $limit = 5) {
        $paginator = new Paginator($dql);
        $paginator->getQuery()
                ->setFirstResult($limit * ($page - 1))
                ->setMaxResults($limit);

        return $paginator;
    }

    public function getImage($gallery, $image) {

        $query = $this->getEntityManager()
                ->createQuery(
                'SELECT a FROM DataBundle:Gallery a
                            JOIN a.imagesInGallery q WHERE a = :gallery and q = :media');
        $query->setParameter('gallery', $gallery);
        $query->setParameter('media', $image);
        return $query->getResult();
    }

}
