services:
    mk.jwt.authenticator:
        class: MK\ApiBundle\Security\Authenticator\JwtAuthenticator
        autowire: true
        
    mk.api.response_factory:
        class: MK\ApiBundle\Factory\ApiResponseFactory
    mk.api_exception_subscriber:
        class: MK\ApiBundle\EventListener\ApiExceptionSubscriber
        arguments: ['%kernel.debug%', '@mk.api.response_factory']
        

    mk.api.access_denied.handler:
        class: MK\ApiBundle\Security\Authorization\AccessDeniedHandler
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onAccessDeniedException }